name: trailscraper standard checks pipeline

on:
  push:
    branches:
      - master
      - move-to-uv
  pull_request: 
  schedule:
    - cron: '0 0 1 * *'

permissions: {}

jobs:
  check-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", 3.11, 3.12, 3.13, 3.14 ]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: ./go setup
      - name: Check Code Style
        run: ./go check
      - name: Run Tests
        run: ./go test
      - name: Build artifacts
        run: ./go build-artifacts
      - name: Test artifacts can be installed and run correctly
        run: PYTHON_VERSION=${{ matrix.python-version }} ./go smoketest-artifacts
      - name: Build docker container
        run: PYTHON_VERSION=${{ matrix.python-version }} ./go build-docker
      - name: Test docker container runs correctly
        run: ./go smoketest-docker
  all-tests-green: # to match in branch protection rules that don't work for matrix jobs
    needs: check-and-test
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Dummy, to have a branch condition"
  codeql-analyse:
    permissions:
      security-events: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
      - name: Autobuild
        uses: github/codeql-action/autobuild@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
